//! `panopt up` - boot or attach the cockpit.

use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

use crate::{daemon, mcp, paths};

/// The cockpit layout: five fixed plugin panes stacked vertically on the
/// left (one per resource kind) and a single content pane on the right.
///
/// Each plugin pane is one Zellij plugin instance running the same wasm
/// binary, configured by a distinct `mode` value (`todos`, `agents`,
/// `terminals`, `commands`, `scratchpads`). Zellij keys plugin identity on
/// `(URL, configuration)`, so the five panes are five distinct instances.
/// Layout-pinned in the `ui` tab template, so adding or removing panes on
/// the right cannot reshape them.
///
/// The content pane starts as one empty `panopt _viewer`; selections in any
/// of the five panes swap their target into that one slot, suppressing
/// whatever was there. The user is free to split the content pane to make
/// further slots.
///
/// `{{PROJECT}}`, `{{WASM}}`, `{{PANOPT_BIN}}`, and `{{PORT}}` are
/// substituted by [`render_layout`]; each may appear more than once.
const LAYOUT_TEMPLATE: &str = r#"// PANopt cockpit - generated by `panopt up`. Regenerated on each run.
// Five plugin panes stack vertically on the LEFT (~25% column), one per
// resource kind; a single content pane sits on the RIGHT. Selections swap
// into that one pane - suppressed panes keep running, hidden.
layout {
    cwd "{{PROJECT}}"

    // The fixed shell of every tab: five plugin panes pinned left (one per
    // mode), the content pane on the right flows into the `children` slot.
    tab_template name="ui" {
        pane split_direction="vertical" {
            pane size="25%" split_direction="horizontal" {
                pane size="30%" {
                    plugin location="file:{{WASM}}" {
                        mode "todos"
                        ws "{{PROJECT}}"
                        panopt_bin "{{PANOPT_BIN}}"
                        port "{{PORT}}"
                    }
                }
                pane size="15%" {
                    plugin location="file:{{WASM}}" {
                        mode "agents"
                        ws "{{PROJECT}}"
                        panopt_bin "{{PANOPT_BIN}}"
                        port "{{PORT}}"
                    }
                }
                pane size="15%" {
                    plugin location="file:{{WASM}}" {
                        mode "terminals"
                        ws "{{PROJECT}}"
                        panopt_bin "{{PANOPT_BIN}}"
                        port "{{PORT}}"
                    }
                }
                pane size="15%" {
                    plugin location="file:{{WASM}}" {
                        mode "commands"
                        ws "{{PROJECT}}"
                        panopt_bin "{{PANOPT_BIN}}"
                        port "{{PORT}}"
                    }
                }
                pane size="25%" {
                    plugin location="file:{{WASM}}" {
                        mode "scratchpads"
                        ws "{{PROJECT}}"
                        panopt_bin "{{PANOPT_BIN}}"
                        port "{{PORT}}"
                    }
                }
            }
            pane {
                children
            }
        }
    }

    // Initial state: the five plugin panes plus one empty document viewer.
    ui {
        pane command="{{PANOPT_BIN}}" {
            args "_viewer" "--slot" "main" "--port" "{{PORT}}"
        }
    }
}
"#;

/// Zellij's stock keybinding that enters scroll mode, and the cockpit's
/// replacement. [`render_config`] rewrites the first to the second so a bare
/// Ctrl-S is left unbound and reaches the focused pane - the todo form
/// (`panopt todo edit`) saves on it. Scroll mode moves to Ctrl-Shift-S.
///
/// Zellij layouts cannot carry keybindings (`keybinds` is not a layout node),
/// so this is applied to a generated config handed to Zellij via `--config`.
const SCROLL_BIND_FROM: &str = r#"bind "Ctrl s" { SwitchToMode "scroll"; }"#;
const SCROLL_BIND_TO: &str = r#"bind "Ctrl Shift s" { SwitchToMode "scroll"; }"#;

/// Zellij's stock Alt-N binding opens a shell pane. The cockpit retargets it
/// to send the `panopt:spawn-blank-pane` pipe to the Todos plugin pane,
/// which (as cockpit gatekeeper) spawns a fresh empty-viewer pane with its
/// own routing slot - so any of the five plugin panes can later re-point it
/// on a selection.
///
/// Why `Run "zellij" "action" "pipe" ...` instead of `MessagePlugin`: Zellij's
/// KDL parser folds `MessagePlugin`'s metadata fields (`name`, `payload`,
/// `cwd`, `launch_new`, ...) into the plugin's user-configuration map. The
/// runtime then keys plugin identity on `(URL, configuration)`, so a
/// `MessagePlugin` keybind whose configuration has any of those metadata
/// keys can never match a layout plugin whose configuration does not - Zellij
/// launches a *second* plugin instance instead. `zellij action pipe` goes
/// through the running session's IPC bus and reaches the existing plugin
/// without that mismatch. The cost is a brief transient pane while the CLI
/// runs; `close_on_exit true` closes it the moment the pipe is sent.
///
/// Why `--plugin-configuration "mode=todos"`: with five plugin instances
/// (one per mode), an unfiltered pipe broadcasts to all five. Narrowing to
/// `mode=todos` delivers the message only to the gatekeeper. The plugin
/// also early-returns from `pipe()` on non-Todos panes - belt-and-braces if
/// the filter ever fails to match.
const NEW_PANE_BIND_FROM: &str = r#"bind "Alt n" { NewPane; }"#;
const NEW_PANE_BIND_TO: &str = r#"bind "Alt n" { Run "zellij" "action" "pipe" "--name" "panopt:spawn-blank-pane" "--plugin-configuration" "mode=todos" { close_on_exit true; }; }"#;

/// Zellij's stock close/quit keybinds, rewritten to pipe a request to the
/// Todos plugin pane (cockpit gatekeeper) instead of acting immediately.
/// The plugin refuses the action when an active item would be lost and
/// otherwise force-closes through the plugin API. The `pipe` mechanism is
/// the same as Alt-N's rewrite - see [`NEW_PANE_BIND_FROM`] for why it goes
/// through `zellij action pipe` rather than `MessagePlugin`, and for the
/// `--plugin-configuration "mode=todos"` narrowing.
///
/// The defaults dump these in pane mode, tab mode, search mode (`x` =
/// CloseFocus), and a shared_except locked block (`Ctrl q` = Quit). Each FROM
/// here is the exact text the dump emits; [`str::replace`] catches every
/// occurrence so all modes funnel through the same pipe.
const CLOSE_FOCUS_BIND_FROM: &str = r#"bind "x" { CloseFocus; SwitchToMode "Normal"; }"#;
const CLOSE_FOCUS_BIND_TO: &str = r#"bind "x" { Run "zellij" "action" "pipe" "--name" "panopt:close-focus-request" "--plugin-configuration" "mode=todos" { close_on_exit true; }; SwitchToMode "Normal"; }"#;
const CLOSE_TAB_BIND_FROM: &str = r#"bind "x" { CloseTab; SwitchToMode "Normal"; }"#;
const CLOSE_TAB_BIND_TO: &str = r#"bind "x" { Run "zellij" "action" "pipe" "--name" "panopt:close-tab-request" "--plugin-configuration" "mode=todos" { close_on_exit true; }; SwitchToMode "Normal"; }"#;
const QUIT_BIND_FROM: &str = r#"bind "Ctrl q" { Quit; }"#;
const QUIT_BIND_TO: &str = r#"bind "Ctrl q" { Run "zellij" "action" "pipe" "--name" "panopt:quit-request" "--plugin-configuration" "mode=todos" { close_on_exit true; }; }"#;

/// Mouse-mode KDL toggle. The cockpit relies on mouse events reaching the
/// inner program: `panopt _viewer` does its own click-to-position-cursor and
/// drag-to-select in form panes, and globally-on mouse mode lets agent panes
/// reach the terminal emulator's modifier-drag-to-select. Zellij's stock
/// default is `true` already, but a user's customized config could have it
/// off; [`ensure_mouse_mode_enabled`] forces it on either way.
const MOUSE_MODE_OFF: &str = "mouse_mode false";
const MOUSE_MODE_ON: &str = "mouse_mode true";

/// `panopt up` - ensure the daemon, then create or attach this project's
/// cockpit Zellij session.
///
/// `host`, when supplied, is forwarded to `panoptd --host` so the daemon
/// binds to a non-loopback interface (`0.0.0.0` to accept connections from
/// other machines). Ignored if the daemon is already running - the bind
/// address only matters when this call starts a fresh `panoptd`.
pub fn run(plugin: Option<PathBuf>, host: Option<String>, port: u16) -> Result<()> {
    if std::env::var_os("ZELLIJ").is_some() {
        bail!("run `panopt up` from a plain shell, not inside Zellij");
    }

    daemon::ensure(host.as_deref(), port)?;
    mcp::ensure()?;

    let project = std::env::current_dir().context("reading the current directory")?;
    let project = std::fs::canonicalize(&project)
        .with_context(|| format!("no such directory: {}", project.display()))?;
    let session = session_name(&project);

    match session_state(&session) {
        SessionState::Live => {
            println!("attaching to cockpit `{session}`");
            let err = Command::new("zellij").arg("attach").arg(&session).exec();
            return Err(err).context("could not exec `zellij attach`");
        }
        SessionState::Dead => {
            // Quitting a cockpit leaves a dead, resurrectable Zellij session;
            // clear it so `panopt up` boots a fresh one. Daemon state (todos,
            // scratchpads) lives in SQLite and is unaffected.
            println!("clearing the dead cockpit `{session}`");
            let cleared = Command::new("zellij")
                .arg("delete-session")
                .arg(&session)
                .status()
                .context("running `zellij delete-session`")?;
            if !cleared.success() {
                bail!(
                    "could not clear the dead session `{session}`; \
                     remove it with `zellij delete-session {session}`"
                );
            }
        }
        SessionState::Absent => {}
    }

    let wasm = match plugin {
        Some(p) => p,
        None => default_plugin_wasm()
            .context("could not find the panopt-zellij plugin .wasm; pass --plugin <path>")?,
    };
    if let Err(e) = ensure_clipboard_permission_granted(&wasm) {
        eprintln!(
            "warning: could not pre-grant Zellij's `WriteToClipboard` \
             permission for the sidebar plugin ({e:#}); the cockpit will \
             still come up but the form's drag-to-copy may not reach the \
             system clipboard until you approve the permission prompt"
        );
    }
    let layout = render_layout(&project, &wasm, port)?;
    let config = match render_config() {
        Ok(path) => Some(path),
        Err(e) => {
            eprintln!(
                "warning: could not prepare the cockpit's Zellij config ({e:#}); \
                 starting with your default keybindings - Ctrl-S in the todo form \
                 may be swallowed by Zellij, and Alt-N opens a shell instead of a \
                 blank viewer pane"
            );
            None
        }
    };
    println!("starting cockpit `{session}`");
    // `--new-session-with-layout` always creates a fresh session; plain
    // `--layout` alongside `--session` would instead try to add tabs to an
    // existing session of that name. `--config` points Zellij at the generated
    // cockpit config, which frees Ctrl-S for panes so the todo form saves on it.
    let mut zellij = Command::new("zellij");
    zellij.arg("--session").arg(&session);
    if let Some(config) = &config {
        zellij.arg("--config").arg(config);
    }
    zellij.arg("--new-session-with-layout").arg(&layout);
    let err = zellij.exec();
    Err(err).context("could not exec `zellij`")
}

/// The cockpit session name for a project: `panopt-<basename>-<hash>`. The
/// basename is reduced to characters Zellij accepts; the hash is a short
/// fingerprint of the canonical project path, so two projects sharing a
/// basename (`~/a/frontend`, `~/b/frontend`) land on distinct sessions
/// instead of one silently attaching to the other's cockpit.
fn session_name(project: &Path) -> String {
    let base = project
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project");
    let safe: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let hash = short_path_hash(project);
    format!("panopt-{safe}-{hash}")
}

/// Stable 7-hex-char fingerprint of the canonical project path. Used as the
/// disambiguating suffix on the cockpit session name; see [`session_name`].
fn short_path_hash(project: &Path) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    project.hash(&mut hasher);
    let h = hasher.finish();
    format!("{h:016x}").chars().take(7).collect()
}

/// Whether a Zellij session named `name` exists, and if so whether it is live
/// or dead (exited but still resurrectable).
enum SessionState {
    Absent,
    Live,
    Dead,
}

fn session_state(name: &str) -> SessionState {
    let Ok(out) = Command::new("zellij").arg("list-sessions").output() else {
        return SessionState::Absent;
    };
    let text = strip_ansi(&String::from_utf8_lossy(&out.stdout));
    for line in text.lines() {
        if line.split_whitespace().next() == Some(name) {
            return if line.contains("EXITED") {
                SessionState::Dead
            } else {
                SessionState::Live
            };
        }
    }
    SessionState::Absent
}

/// Drop ANSI escape sequences so `zellij list-sessions` output can be parsed.
fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' {
            // Skip a CSI sequence up to and including its final letter.
            for n in chars.by_ref() {
                if n.is_ascii_alphabetic() {
                    break;
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Locate the plugin `.wasm` from a dev build, relative to this binary
/// (`<repo>/target/<profile>/panopt`).
fn default_plugin_wasm() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let repo = exe.ancestors().nth(3)?;
    let wasm = repo.join("crates/panopt-zellij/target/wasm32-wasip1/release/panopt-zellij.wasm");
    wasm.is_file().then_some(wasm)
}

/// Render the cockpit layout for `project`, write it to disk, return its path.
fn render_layout(project: &Path, wasm: &Path, port: u16) -> Result<PathBuf> {
    let panopt_bin = std::env::current_exe().context("locating the panopt binary")?;
    let body = LAYOUT_TEMPLATE
        .replace("{{PROJECT}}", &project.to_string_lossy())
        .replace("{{WASM}}", &wasm.to_string_lossy())
        .replace("{{PANOPT_BIN}}", &panopt_bin.to_string_lossy())
        .replace("{{PORT}}", &port.to_string());
    let path = paths::cockpit_layout()?;
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// Free Ctrl-S for panes by retargeting Zellij's scroll-mode keybinding to
/// Ctrl-Shift-S. Returns the rewritten config and whether the binding was
/// actually found - a reformatted or unusually customized config may not carry
/// it in the expected form.
fn retarget_scroll_binding(base: &str) -> (String, bool) {
    let tweaked = base.replace(SCROLL_BIND_FROM, SCROLL_BIND_TO);
    let changed = tweaked != base;
    (tweaked, changed)
}

/// Retarget Zellij's Alt-N keybinding to `Run` of `zellij action pipe`, which
/// pipes a message to the sidebar plugin telling it to spawn a blank viewer
/// pane.
fn retarget_new_pane_binding(base: &str) -> (String, bool) {
    let tweaked = base.replace(NEW_PANE_BIND_FROM, NEW_PANE_BIND_TO);
    let changed = tweaked != base;
    (tweaked, changed)
}

/// Pre-grant Zellij's `WriteToClipboard` permission for the sidebar plugin
/// so the auto-locked cockpit can copy form selections without a runtime
/// permission dialog ("can the plugin access your clipboard?") that the
/// user might not see or might dismiss with the wrong button.
///
/// The cache lives at `~/.cache/zellij/permissions.kdl` (Zellij's exact
/// path on Linux; on macOS Zellij actually keeps it elsewhere - we still
/// write to the same `dirs::cache_dir()`-derived path, which is good
/// enough for users who run the cockpit on Linux as Zellij itself
/// reads from the matching location there).
///
/// File format (Zellij's own, parsed by `PermissionCache::from_string`):
///
/// ```kdl
/// "<absolute wasm path>" {
///     ChangeApplicationState
///     RunCommands
///     ReadApplicationState
///     WriteToClipboard
/// }
/// ```
///
/// If the user already approved the other three (the run dialog has been
/// dismissed at least once), only `WriteToClipboard` is added inside the
/// existing block. If the entry doesn't exist yet a fresh block is
/// appended. Either way the file is created if missing.
fn ensure_clipboard_permission_granted(wasm: &Path) -> Result<()> {
    let cache_dir = dirs::cache_dir().context("locating the user cache directory")?;
    let cache_file = cache_dir.join("zellij").join("permissions.kdl");
    let wasm_str = wasm.to_string_lossy().to_string();

    let existing = match std::fs::read_to_string(&cache_file) {
        Ok(s) => s,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => {
            return Err(e).with_context(|| format!("reading {}", cache_file.display()));
        }
    };

    let Some(new_content) = grant_clipboard_in_cache(&existing, &wasm_str) else {
        // Already present; nothing to do.
        return Ok(());
    };

    if let Some(parent) = cache_file.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(&cache_file, new_content)
        .with_context(|| format!("writing {}", cache_file.display()))?;
    Ok(())
}

/// Pure transform: given the current `permissions.kdl` contents and our
/// plugin's wasm path, return the updated contents if a write is needed
/// (i.e. our plugin's entry was missing or did not list
/// `WriteToClipboard`), or `None` if no change.
///
/// Hand-rolled string surgery rather than a KDL parser dep. Format is
/// regular enough that finding `"<path>" {` plus brace balancing covers
/// every shape Zellij writes itself.
fn grant_clipboard_in_cache(existing: &str, wasm_path: &str) -> Option<String> {
    const GRANT: &str = "WriteToClipboard";
    let key = format!("\"{wasm_path}\"");
    if let Some(start) = existing.find(&key) {
        // Found a block for our plugin; splice in WriteToClipboard if
        // missing, else no-op.
        let rel_open = existing[start..].find('{')?;
        let open = start + rel_open;
        let mut depth: i32 = 0;
        let mut close: Option<usize> = None;
        for (i, b) in existing.as_bytes().iter().enumerate().skip(open) {
            match b {
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        close = Some(i);
                        break;
                    }
                }
                _ => {}
            }
        }
        let close = close?;
        let body = &existing[open + 1..close];
        if body.contains(GRANT) {
            return None;
        }
        let mut out = String::with_capacity(existing.len() + GRANT.len() + 8);
        out.push_str(&existing[..close]);
        out.push_str("    ");
        out.push_str(GRANT);
        out.push('\n');
        out.push_str(&existing[close..]);
        return Some(out);
    }
    // No block for this plugin yet; append a fresh one with the four
    // permissions the plugin actually requests today.
    let mut out = String::from(existing);
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&format!(
        "\"{wasm_path}\" {{\n    \
            ReadApplicationState\n    \
            ChangeApplicationState\n    \
            RunCommands\n    \
            WriteToClipboard\n\
         }}\n"
    ));
    Some(out)
}

/// Inject extra `locked`-mode keybinds into the base config's first
/// `keybinds` block so the cockpit-essential keys keep working when the
/// plugin auto-locks a content pane. Zellij's stock dump puts these in
/// `shared_except "locked"`, which strips them under Locked mode - without
/// this injection a user whose focused viewer / agent pane has just been
/// auto-locked cannot move to another pane (Alt-arrows), spawn a new one
/// (the cockpit's rewritten Alt-N), or quit (the rewritten Ctrl-Q) without
/// first pressing Ctrl-G to escape - and the plugin would immediately
/// re-lock them on the next PaneUpdate.
///
/// Appending a *second* `keybinds { ... }` block does not work: Zellij only
/// reads the first top-level `keybinds` node and silently ignores the rest
/// (see the `TODO` at `zellij-utils kdl/mod.rs:4862`). So we walk the base
/// config, find the first `locked {` header, balance braces to its matching
/// close, and splice our binds in just before it. The bool reports whether
/// the splice succeeded - a config without a `locked` block (e.g. fully
/// custom and unconventional) gets a warning so the user can wire it by
/// hand.
fn inject_locked_keybinds(base: &str) -> (String, bool) {
    let key = "locked {";
    let Some(start) = base.find(key) else {
        return (base.to_string(), false);
    };
    // Byte index of the `{` itself - balance from here.
    let open = start + key.len() - 1;
    let bytes = base.as_bytes();
    let mut depth: i32 = 0;
    let mut close = None;
    for (i, b) in bytes.iter().enumerate().skip(open) {
        match b {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    close = Some(i);
                    break;
                }
            }
            _ => {}
        }
    }
    let Some(close) = close else {
        return (base.to_string(), false);
    };
    let extras = locked_extra_binds();
    let mut out = String::with_capacity(base.len() + extras.len());
    out.push_str(&base[..close]);
    out.push_str(&extras);
    out.push_str(&base[close..]);
    (out, true)
}

/// Inject a `shared { ... }` block carrying global `PageUp`/`PageDown`
/// bindings into the base config's first `keybinds` block. Directly binding
/// the action - rather than entering scroll mode first - keeps the gesture
/// transparent: Zellij scrolls the focused pane's scrollback and
/// auto-returns to the bottom on the next input or output. Because
/// `shared` applies to every mode (including locked), the bindings reach
/// the user whether the plugin has auto-locked the pane or not, and the
/// keypress never reaches the inner program (so Claude can't repurpose
/// PageUp for prompt history).
///
/// Splice strategy mirrors [`inject_locked_keybinds`]: find the first
/// `keybinds` node, jump to its opening `{`, balance braces to the matching
/// close, and insert the `shared { ... }` block just before that close so
/// it sits at the same depth as the other mode blocks.
fn inject_page_scroll_keybinds(base: &str) -> (String, bool) {
    let key = "keybinds";
    let Some(kb_start) = base.find(key) else {
        return (base.to_string(), false);
    };
    // The `keybinds` node may carry attributes (e.g. `clear-defaults=true`)
    // before its opening brace; skip ahead to that brace.
    let Some(open_offset) = base[kb_start + key.len()..].find('{') else {
        return (base.to_string(), false);
    };
    let open = kb_start + key.len() + open_offset;
    let bytes = base.as_bytes();
    let mut depth: i32 = 0;
    let mut close = None;
    for (i, b) in bytes.iter().enumerate().skip(open) {
        match b {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    close = Some(i);
                    break;
                }
            }
            _ => {}
        }
    }
    let Some(close) = close else {
        return (base.to_string(), false);
    };
    let extras = page_scroll_shared_block();
    let mut out = String::with_capacity(base.len() + extras.len());
    out.push_str(&base[..close]);
    out.push_str(&extras);
    out.push_str(&base[close..]);
    (out, true)
}

/// The `shared { ... }` block spliced in by [`inject_page_scroll_keybinds`].
/// Four-space indent (one level inside the surrounding `keybinds { ... }`)
/// to match the mode blocks already there.
///
/// `PageScrollUp` / `PageScrollDown` (not `ScrollUp` / `ScrollDown`) move a
/// full visible-height page at a time, matching the gesture users expect
/// from PageUp; the bare `ScrollUp` is a single-line action and would feel
/// like a slow arrow-key.
fn page_scroll_shared_block() -> String {
    "    shared {\n        \
        bind \"PageUp\" { PageScrollUp; }\n        \
        bind \"PageDown\" { PageScrollDown; }\n    \
    }\n"
    .to_string()
}

/// The body of bindings injected into the existing locked block by
/// [`inject_locked_keybinds`]. Indentation matches the typical eight-space
/// inner indent of a Zellij `mode { bind ... }` body so the spliced lines
/// sit visually alongside whatever was already there. The Alt-N and Ctrl-Q
/// binds reuse the cockpit's pipe-gated rewrites so spawn and quit still go
/// through the sidebar gatekeeper.
fn locked_extra_binds() -> String {
    format!(
        "        bind \"Alt Left\" {{ MoveFocusOrTab \"Left\"; }}\n        \
         bind \"Alt Right\" {{ MoveFocusOrTab \"Right\"; }}\n        \
         bind \"Alt Up\" {{ MoveFocus \"Up\"; }}\n        \
         bind \"Alt Down\" {{ MoveFocus \"Down\"; }}\n        \
         {NEW_PANE_BIND_TO}\n        \
         {QUIT_BIND_TO}\n    "
    )
}

/// Force `mouse_mode true` in the generated config. Replaces an explicit
/// `mouse_mode false` if the user's base config has one; otherwise appends
/// the line iff `mouse_mode true` is not already present. Either way, the
/// generated cockpit config carries an explicit on, so the auto-locked mode
/// flip never lands users in a state where mouse events stop reaching their
/// content panes.
fn ensure_mouse_mode_enabled(base: &str) -> String {
    let flipped = base.replace(MOUSE_MODE_OFF, MOUSE_MODE_ON);
    if flipped.contains(MOUSE_MODE_ON) {
        return flipped;
    }
    let mut out = flipped;
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(MOUSE_MODE_ON);
    out.push('\n');
    out
}

/// Retarget every CloseFocus/CloseTab/Quit keybind to `Run` of
/// `zellij action pipe`, sending the request to the sidebar plugin instead of
/// acting immediately. The plugin gates these against active items and either
/// refuses (showing a floating dialog) or force-closes via the plugin API,
/// which bypasses the rewritten keybinds.
///
/// The returned tuple reports whether each rewrite was found - users with a
/// reformatted or heavily-customized config may have moved them; we warn so
/// the user knows the gate has gaps. The default Zellij dump emits the
/// CloseFocus binding in multiple modes; `str::replace` catches every copy.
fn retarget_close_bindings(base: &str) -> (String, bool, bool, bool) {
    let after_close_focus = base.replace(CLOSE_FOCUS_BIND_FROM, CLOSE_FOCUS_BIND_TO);
    let close_focus_changed = after_close_focus != base;
    let after_close_tab = after_close_focus.replace(CLOSE_TAB_BIND_FROM, CLOSE_TAB_BIND_TO);
    let close_tab_changed = after_close_tab != after_close_focus;
    let after_quit = after_close_tab.replace(QUIT_BIND_FROM, QUIT_BIND_TO);
    let quit_changed = after_quit != after_close_tab;
    (
        after_quit,
        close_focus_changed,
        close_tab_changed,
        quit_changed,
    )
}

/// Locate the Zellij config file Zellij itself would load, following its own
/// lookup order: `$ZELLIJ_CONFIG_FILE`, `$ZELLIJ_CONFIG_DIR/config.kdl`,
/// `$XDG_CONFIG_HOME/zellij/config.kdl`, then `~/.config/zellij/config.kdl`.
/// `None` when the user keeps no config and relies on Zellij's defaults.
fn user_zellij_config() -> Option<PathBuf> {
    if let Some(file) = std::env::var_os("ZELLIJ_CONFIG_FILE") {
        let path = PathBuf::from(file);
        if path.is_file() {
            return Some(path);
        }
    }
    let config_kdl = |dir: PathBuf| {
        let path = dir.join("config.kdl");
        path.is_file().then_some(path)
    };
    if let Some(dir) = std::env::var_os("ZELLIJ_CONFIG_DIR") {
        if let Some(path) = config_kdl(PathBuf::from(dir)) {
            return Some(path);
        }
    }
    if let Some(dir) = std::env::var_os("XDG_CONFIG_HOME") {
        if let Some(path) = config_kdl(PathBuf::from(dir).join("zellij")) {
            return Some(path);
        }
    }
    dirs::home_dir().and_then(|home| config_kdl(home.join(".config").join("zellij")))
}

/// The Zellij config to derive the cockpit's from: the user's own config, or -
/// when they keep none - Zellij's built-in defaults via `zellij setup
/// --dump-config`.
fn base_zellij_config() -> Result<String> {
    if let Some(path) = user_zellij_config() {
        return std::fs::read_to_string(&path)
            .with_context(|| format!("reading the Zellij config {}", path.display()));
    }
    let out = Command::new("zellij")
        .args(["setup", "--dump-config"])
        .output()
        .context("running `zellij setup --dump-config`")?;
    if !out.status.success() {
        bail!("`zellij setup --dump-config` exited with a failure");
    }
    String::from_utf8(out.stdout).context("`zellij setup --dump-config` produced invalid UTF-8")
}

/// Generate the cockpit's Zellij config - the user's config with Ctrl-S freed
/// for panes so the todo form's save keybinding reaches it, and Alt-N
/// retargeted to spawn a blank viewer pane via the sidebar plugin - write it
/// to disk, and return its path. Regenerated on each run, so it tracks the
/// user's own config.
fn render_config() -> Result<PathBuf> {
    let base = base_zellij_config()?;
    let (tweaked, scroll_changed) = retarget_scroll_binding(&base);
    if !scroll_changed {
        eprintln!(
            "warning: Zellij's `Ctrl s` scroll binding was not found in the \
             expected form, so it could not be remapped; Ctrl-S in the todo \
             form may be swallowed by Zellij"
        );
    }
    let (tweaked, new_pane_changed) = retarget_new_pane_binding(&tweaked);
    if !new_pane_changed {
        eprintln!(
            "warning: Zellij's `Alt n` `NewPane` binding was not found in the \
             expected form, so it could not be remapped; Alt-N will open a \
             shell rather than a blank viewer pane"
        );
    }
    let (tweaked, close_focus_changed, close_tab_changed, quit_changed) =
        retarget_close_bindings(&tweaked);
    if !close_focus_changed {
        eprintln!(
            "warning: Zellij's `CloseFocus` binding was not found in the \
             expected form, so it could not be gated; closing a pane will \
             bypass the active-item guard"
        );
    }
    if !close_tab_changed {
        eprintln!(
            "warning: Zellij's `CloseTab` binding was not found in the \
             expected form, so it could not be gated; closing a tab will \
             bypass the active-item guard"
        );
    }
    if !quit_changed {
        eprintln!(
            "warning: Zellij's `Ctrl q` `Quit` binding was not found in the \
             expected form, so it could not be gated; quitting will bypass \
             the active-item guard"
        );
    }
    let tweaked = ensure_mouse_mode_enabled(&tweaked);
    let (tweaked, locked_injected) = inject_locked_keybinds(&tweaked);
    if !locked_injected {
        eprintln!(
            "warning: no `locked {{ ... }}` block was found in your Zellij \
             config, so the cockpit could not inject Alt-arrow navigation \
             and the rewritten Alt-N / Ctrl-Q binds into Locked mode; while \
             focused on a content pane (which the sidebar auto-locks), those \
             keys will be inert and you will have to press Ctrl-G to escape \
             before moving focus or quitting"
        );
    }
    let (tweaked, page_scroll_injected) = inject_page_scroll_keybinds(&tweaked);
    if !page_scroll_injected {
        eprintln!(
            "warning: no top-level `keybinds {{ ... }}` block was found in \
             your Zellij config, so the cockpit could not bind PageUp / \
             PageDown to direct scroll actions; those keys will instead \
             reach the inner program (Claude may repurpose them for prompt \
             history) and the scrollback gesture will not work"
        );
    }
    let body = format!(
        "// PANopt cockpit Zellij config - generated by `panopt up`, regenerated\n\
         // each run from your own Zellij config. Zellij's Ctrl-S (scroll mode)\n\
         // is remapped to Ctrl-Shift-S so a bare Ctrl-S reaches panes: the todo\n\
         // form (`panopt todo edit`) saves on it. Alt-N is retargeted to pipe\n\
         // a `panopt:spawn-blank-pane` message to the sidebar plugin, which\n\
         // spawns a blank viewer pane with its own routing slot. CloseFocus,\n\
         // CloseTab, and Quit are retargeted to pipe close-request messages to\n\
         // the sidebar, which gates them against active agents/commands/terminals.\n\
         // `mouse_mode true` is forced so the auto-locked input mode (set by\n\
         // the plugin when focus lands on a content pane) doesn't strand the\n\
         // user without mouse events reaching the viewer / terminal panes.\n\
         // Alt-arrow pane navigation plus the rewritten Alt-N and Ctrl-Q are\n\
         // spliced into the existing `locked` block (a second top-level\n\
         // `keybinds` block does not work - Zellij only reads the first one),\n\
         // so the user can leave a content pane, spawn a new one, or quit\n\
         // without a Ctrl-G escape that would just be re-locked on the next\n\
         // PaneUpdate. PageUp / PageDown go into a `shared {{ ... }}` block\n\
         // so they hit ScrollUp/ScrollDown directly in every mode - the\n\
         // pane's Zellij scrollback scrolls and auto-returns on next I/O,\n\
         // and the keys never reach the inner program.\n\
         {tweaked}"
    );
    let path = paths::cockpit_config()?;
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::{
        ensure_mouse_mode_enabled, grant_clipboard_in_cache, inject_locked_keybinds,
        inject_page_scroll_keybinds, retarget_close_bindings, retarget_new_pane_binding,
        retarget_scroll_binding, session_name, strip_ansi, LAYOUT_TEMPLATE,
    };
    use std::path::Path;

    #[test]
    fn session_name_sanitizes_the_basename() {
        let n = session_name(Path::new("/Users/x/p/panopt-demo"));
        assert!(n.starts_with("panopt-panopt-demo-"), "got {n}");
        let n2 = session_name(Path::new("/a/b/My Proj.v2"));
        assert!(n2.starts_with("panopt-My-Proj-v2-"), "got {n2}");
    }

    #[test]
    fn session_name_disambiguates_same_basename() {
        let a = session_name(Path::new("/home/u/a/frontend"));
        let b = session_name(Path::new("/home/u/b/frontend"));
        assert_ne!(a, b);
        assert!(a.starts_with("panopt-frontend-"));
        assert!(b.starts_with("panopt-frontend-"));
    }

    #[test]
    fn strip_ansi_removes_escape_sequences() {
        assert_eq!(strip_ansi("\u{1b}[32;1mname\u{1b}[m rest"), "name rest");
    }

    #[test]
    fn retarget_scroll_binding_moves_ctrl_s_to_ctrl_shift_s() {
        let base = "    bind \"Ctrl s\" { SwitchToMode \"scroll\"; }\n";
        let (tweaked, changed) = retarget_scroll_binding(base);
        assert!(changed);
        assert_eq!(
            tweaked,
            "    bind \"Ctrl Shift s\" { SwitchToMode \"scroll\"; }\n"
        );
        // The scroll-mode exit binding (`Ctrl s` -> normal) is a different
        // string and must be left untouched.
        let exit = "bind \"Ctrl s\" { SwitchToMode \"normal\"; }";
        assert_eq!(retarget_scroll_binding(exit), (exit.to_string(), false));
    }

    #[test]
    fn retarget_scroll_binding_reports_when_absent() {
        let (text, changed) = retarget_scroll_binding("keybinds {}\n");
        assert!(!changed);
        assert_eq!(text, "keybinds {}\n");
    }

    #[test]
    fn retarget_new_pane_binding_swaps_in_the_pipe_action() {
        let base = "    bind \"Alt n\" { NewPane; }\n";
        let (tweaked, changed) = retarget_new_pane_binding(base);
        assert!(changed);
        // The pipe goes through Zellij's IPC bus rather than MessagePlugin, so
        // it reaches the existing plugin pane without the user-config mismatch
        // that would otherwise have Zellij spawn a second plugin instance.
        assert!(
            tweaked.contains("Run \"zellij\" \"action\" \"pipe\""),
            "expected the Run action with `zellij action pipe`: {tweaked}"
        );
        assert!(tweaked.contains("\"panopt:spawn-blank-pane\""));
        // Narrowed to the Todos gatekeeper so only one of the five plugin
        // panes acts on the pipe.
        assert!(tweaked.contains("\"--plugin-configuration\" \"mode=todos\""));
        // The transient pane must close itself as soon as the CLI exits, so
        // the user just sees a brief flash and then the new viewer pane.
        assert!(tweaked.contains("close_on_exit true"));
    }

    #[test]
    fn retarget_new_pane_binding_reports_when_absent() {
        let (text, changed) = retarget_new_pane_binding("keybinds {}\n");
        assert!(!changed);
        assert_eq!(text, "keybinds {}\n");
    }

    #[test]
    fn retarget_close_bindings_funnels_all_three_actions_through_pipes() {
        // A fragment that mirrors the default Zellij dump: CloseFocus appears
        // in two modes (pane and search) - both must be rewritten - and
        // CloseTab and Quit appear once each.
        let base = "\
            pane {\n        \
                bind \"x\" { CloseFocus; SwitchToMode \"Normal\"; }\n    \
            }\n    \
            tab {\n        \
                bind \"x\" { CloseTab; SwitchToMode \"Normal\"; }\n    \
            }\n    \
            search {\n        \
                bind \"x\" { CloseFocus; SwitchToMode \"Normal\"; }\n    \
            }\n    \
            shared_except \"locked\" {\n        \
                bind \"Ctrl q\" { Quit; }\n    \
            }\n";
        let (tweaked, close_focus, close_tab, quit) = retarget_close_bindings(base);
        assert!(close_focus, "CloseFocus binding must be rewritten");
        assert!(close_tab, "CloseTab binding must be rewritten");
        assert!(quit, "Quit binding must be rewritten");
        // Every destructive action goes through the same pipe pattern so the
        // Todos plugin pane is the single gatekeeper.
        assert!(tweaked.contains("\"panopt:close-focus-request\""));
        assert!(tweaked.contains("\"panopt:close-tab-request\""));
        assert!(tweaked.contains("\"panopt:quit-request\""));
        // Both CloseFocus occurrences (pane and search modes) are caught.
        assert_eq!(tweaked.matches("\"panopt:close-focus-request\"").count(), 2);
        // Every gated pipe carries the mode=todos narrowing so it reaches
        // only the gatekeeper and not the other four plugin panes. Four
        // occurrences in this fixture: two CloseFocus + one CloseTab + one
        // Quit (the floating dialog's reply is sent from `close_gate.rs`,
        // not this rewrite path).
        assert_eq!(
            tweaked
                .matches("\"--plugin-configuration\" \"mode=todos\"")
                .count(),
            4
        );
        // No raw destructive action remains: every path is gated.
        assert!(!tweaked.contains("CloseFocus"));
        assert!(!tweaked.contains("CloseTab"));
        assert!(!tweaked.contains("{ Quit; }"));
        // The mode return is preserved so the user still leaves pane/tab mode
        // after the pipe is sent - matching the original UX shape.
        assert!(tweaked.contains("SwitchToMode \"Normal\""));
        // Transient pipe panes close themselves the moment the CLI exits.
        assert!(tweaked.contains("close_on_exit true"));
    }

    #[test]
    fn retarget_close_bindings_reports_when_absent() {
        let (text, close_focus, close_tab, quit) = retarget_close_bindings("keybinds {}\n");
        assert!(!close_focus);
        assert!(!close_tab);
        assert!(!quit);
        assert_eq!(text, "keybinds {}\n");
    }

    #[test]
    fn ensure_mouse_mode_enabled_flips_explicit_off() {
        let out = ensure_mouse_mode_enabled("keybinds {}\nmouse_mode false\n");
        assert!(out.contains("mouse_mode true"));
        assert!(!out.contains("mouse_mode false"));
        // No duplicate line gets appended when we flipped an existing one.
        assert_eq!(out.matches("mouse_mode true").count(), 1);
    }

    #[test]
    fn ensure_mouse_mode_enabled_appends_when_absent() {
        let out = ensure_mouse_mode_enabled("keybinds {}\n");
        assert!(out.ends_with("mouse_mode true\n"));
        assert_eq!(out.matches("mouse_mode true").count(), 1);
    }

    #[test]
    fn grant_clipboard_in_cache_appends_a_new_block_when_none_exists() {
        // No entry for our plugin yet: we appended a fresh block carrying
        // all four permissions the plugin actually requests today.
        let updated = grant_clipboard_in_cache("", "/path/to/panopt-zellij.wasm")
            .expect("must change when block is absent");
        assert!(updated.contains(r#""/path/to/panopt-zellij.wasm""#));
        assert!(updated.contains("WriteToClipboard"));
        assert!(updated.contains("ReadApplicationState"));
        assert!(updated.contains("ChangeApplicationState"));
        assert!(updated.contains("RunCommands"));
    }

    #[test]
    fn grant_clipboard_in_cache_appends_only_the_grant_inside_existing_block() {
        // Pre-existing block from a prior run that approved the original
        // three permissions; we splice WriteToClipboard inside it instead
        // of appending a duplicate block.
        let base = "\
\"/path/to/panopt-zellij.wasm\" {
    ChangeApplicationState
    RunCommands
    ReadApplicationState
}
";
        let updated = grant_clipboard_in_cache(base, "/path/to/panopt-zellij.wasm")
            .expect("must change when grant is missing");
        // The grant is in there exactly once.
        assert_eq!(updated.matches("WriteToClipboard").count(), 1);
        // The existing entries survive.
        assert!(updated.contains("ChangeApplicationState"));
        assert!(updated.contains("RunCommands"));
        assert!(updated.contains("ReadApplicationState"));
        // No second block was appended (only one `{` and one `}` for this
        // plugin).
        assert_eq!(
            updated.matches(r#""/path/to/panopt-zellij.wasm""#).count(),
            1
        );
    }

    #[test]
    fn grant_clipboard_in_cache_is_a_noop_when_grant_already_present() {
        let base = "\
\"/p.wasm\" {
    ReadApplicationState
    WriteToClipboard
}
";
        assert_eq!(grant_clipboard_in_cache(base, "/p.wasm"), None);
    }

    #[test]
    fn grant_clipboard_in_cache_leaves_other_plugins_alone() {
        // The cache may carry entries for other plugins; we only touch
        // ours, never the unrelated ones.
        let base = "\
\"/other.wasm\" {
    ReadApplicationState
}
\"/ours.wasm\" {
    ReadApplicationState
}
";
        let updated = grant_clipboard_in_cache(base, "/ours.wasm").expect("must change");
        // Other plugin's block is intact - same single permission, no grant.
        let other_block_start = updated.find(r#""/other.wasm""#).unwrap();
        let ours_block_start = updated.find(r#""/ours.wasm""#).unwrap();
        let other_block = &updated[other_block_start..ours_block_start];
        assert!(!other_block.contains("WriteToClipboard"));
        // Ours got it.
        let ours_block = &updated[ours_block_start..];
        assert!(ours_block.contains("WriteToClipboard"));
    }

    #[test]
    fn inject_locked_keybinds_splices_into_first_locked_block() {
        // A minimal config with a single-bind locked block. After injection
        // the original `Ctrl g` bind must still be present (we splice ahead
        // of the closing brace, not in place of it) and the Alt-arrow +
        // pipe-gated cockpit binds must appear inside the same block.
        let base = "\
keybinds clear-defaults=true {
    locked {
        bind \"Ctrl g\" { SwitchToMode \"normal\"; }
    }
    shared_except \"locked\" {
        bind \"Alt h\" \"Alt Left\" { MoveFocusOrTab \"Left\"; }
    }
}
";
        let (out, ok) = inject_locked_keybinds(base);
        assert!(ok);
        assert!(out.contains(r#"bind "Ctrl g" { SwitchToMode "normal"; }"#));
        assert!(out.contains(r#"bind "Alt Left" { MoveFocusOrTab "Left"; }"#));
        assert!(out.contains(r#"bind "Alt Right" { MoveFocusOrTab "Right"; }"#));
        assert!(out.contains(r#"bind "Alt Up" { MoveFocus "Up"; }"#));
        assert!(out.contains(r#"bind "Alt Down" { MoveFocus "Down"; }"#));
        // The cockpit-rewritten Alt-N and Ctrl-Q binds use the same pipe
        // form they have outside locked so the gatekeeper still sees them.
        assert!(out.contains(r#""panopt:spawn-blank-pane""#));
        assert!(out.contains(r#""panopt:quit-request""#));
        // Each pipe binding includes its gatekeeper narrowing once.
        assert_eq!(
            out.matches(r#""--plugin-configuration" "mode=todos""#)
                .count(),
            2
        );
        // The splice lands inside the `locked` block, not after it. The
        // locked block in the fixture is followed by `shared_except`, so
        // every spliced bind must appear before that header.
        let alt_left = out.find(r#"bind "Alt Left""#).unwrap();
        let shared_except = out.find("shared_except").unwrap();
        assert!(
            alt_left < shared_except,
            "Alt Left bind must be spliced inside the locked block, before \
             the next mode block starts"
        );
    }

    #[test]
    fn inject_locked_keybinds_balances_braces_through_nested_binds() {
        // The locked block already contains an inner `{ ... }` action; the
        // injector must close on the *outer* `}`, not the inner one.
        let base = "\
keybinds {
    locked {
        bind \"Ctrl g\" { SwitchToMode \"normal\"; }
    }
}
";
        let (out, ok) = inject_locked_keybinds(base);
        assert!(ok);
        // The original bind survives and the new binds follow.
        let g_bind = out.find(r#"bind "Ctrl g""#).unwrap();
        let alt_left = out.find(r#"bind "Alt Left""#).unwrap();
        assert!(g_bind < alt_left);
        // The outer `keybinds` block closer survives.
        assert!(out.trim_end().ends_with('}'));
    }

    #[test]
    fn inject_locked_keybinds_reports_when_no_locked_block() {
        let (out, ok) = inject_locked_keybinds("keybinds {\n    normal {}\n}\n");
        assert!(!ok);
        // The base is returned unchanged when there is nothing to splice into.
        assert_eq!(out, "keybinds {\n    normal {}\n}\n");
    }

    #[test]
    fn inject_page_scroll_keybinds_splices_a_shared_block() {
        let base = "\
keybinds clear-defaults=true {
    locked {
        bind \"Ctrl g\" { SwitchToMode \"normal\"; }
    }
    normal {
        bind \"Ctrl p\" { SwitchToMode \"pane\"; }
    }
}
";
        let (out, ok) = inject_page_scroll_keybinds(base);
        assert!(ok);
        // PageUp/PageDown go to direct scroll actions, not into scroll mode -
        // so they don't enter a modal state and auto-return on next I/O.
        assert!(out.contains(r#"bind "PageUp" { PageScrollUp; }"#));
        assert!(out.contains(r#"bind "PageDown" { PageScrollDown; }"#));
        // The block lives inside the top-level `keybinds` body so Zellij's
        // parser actually picks it up (a second top-level `keybinds` block
        // would be silently ignored - see the note in render_config).
        assert!(out.contains("shared {"));
        let shared = out.find("shared {").unwrap();
        let keybinds_open = out.find("keybinds").unwrap();
        let last_brace = out.rfind('}').unwrap();
        assert!(keybinds_open < shared && shared < last_brace);
        // The pre-existing mode blocks survive.
        assert!(out.contains(r#"bind "Ctrl g""#));
        assert!(out.contains(r#"bind "Ctrl p""#));
    }

    #[test]
    fn inject_page_scroll_keybinds_handles_clear_defaults_attribute() {
        // The `clear-defaults=true` attribute sits between `keybinds` and its
        // opening `{`; the brace finder must skip past it rather than match
        // an `=` or `t` as a structural character.
        let base = "keybinds clear-defaults=true {\n    locked {}\n}\n";
        let (out, ok) = inject_page_scroll_keybinds(base);
        assert!(ok);
        assert!(out.contains(r#"bind "PageUp" { PageScrollUp; }"#));
        assert!(out.contains(r#"bind "PageDown" { PageScrollDown; }"#));
    }

    #[test]
    fn inject_page_scroll_keybinds_reports_when_no_keybinds_block() {
        let base = "themes { Catppuccin {} }\n";
        let (out, ok) = inject_page_scroll_keybinds(base);
        assert!(!ok);
        assert_eq!(out, base);
    }

    #[test]
    fn ensure_mouse_mode_enabled_is_idempotent_when_already_on() {
        let base = "keybinds {}\nmouse_mode true\n";
        // A config that already has `mouse_mode true` must not gain a second
        // copy - Zellij's KDL parser would reject the duplicate, and the
        // existing copy already covers us.
        assert_eq!(ensure_mouse_mode_enabled(base), base);
    }

    #[test]
    fn layout_template_has_every_placeholder_filled() {
        let body = LAYOUT_TEMPLATE
            .replace("{{PROJECT}}", "/proj")
            .replace("{{WASM}}", "/w.wasm")
            .replace("{{PANOPT_BIN}}", "/bin/panopt")
            .replace("{{PORT}}", "7600");
        assert!(!body.contains("{{"), "unsubstituted placeholder: {body}");
        assert!(body.contains("file:/w.wasm"));
        assert!(body.contains("port \"7600\""));
    }

    #[test]
    fn layout_template_pins_the_sidebar_and_starts_one_viewer() {
        // The five plugin panes live in the `ui` tab template, so they are pinned.
        assert!(LAYOUT_TEMPLATE.contains("tab_template name=\"ui\""));
        // The one content pane starts as an empty viewer; no swap layouts.
        assert!(LAYOUT_TEMPLATE.contains("\"_viewer\""));
        assert!(LAYOUT_TEMPLATE.contains("\"--slot\" \"main\""));
        assert!(LAYOUT_TEMPLATE.contains("children"));
        assert!(!LAYOUT_TEMPLATE.contains("swap_tiled_layout"));
    }

    #[test]
    fn layout_template_declares_five_plugin_panes_one_per_mode() {
        // The five plugin panes share one wasm; `mode` selects what each
        // renders. Each mode must appear exactly once - misspellings or
        // duplicates would silently disable a pane or collide on the
        // gatekeeper role.
        let body = LAYOUT_TEMPLATE
            .replace("{{PROJECT}}", "/proj")
            .replace("{{WASM}}", "/w.wasm")
            .replace("{{PANOPT_BIN}}", "/bin/panopt")
            .replace("{{PORT}}", "7600");
        for m in ["todos", "agents", "terminals", "commands", "scratchpads"] {
            assert_eq!(
                body.matches(&format!("mode \"{m}\"")).count(),
                1,
                "expected exactly one `mode \"{m}\"` block in:\n{body}"
            );
        }
        // Five plugin blocks, one per mode.
        assert_eq!(body.matches("plugin location=").count(), 5);
        // Still exactly one content viewer at boot.
        assert_eq!(body.matches("\"_viewer\" \"--slot\" \"main\"").count(), 1);
    }
}
