//! `panopt up` - boot or attach the cockpit.

use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

use crate::{daemon, mcp, paths};

/// The cockpit layout: a fixed sidebar plugin pane on the left and a single
/// content pane on the right.
///
/// The sidebar plugin is declared once in the `ui` tab template, so it is
/// pinned full-height on the left. The content pane starts as one empty
/// `panopt _viewer`; the sidebar swaps todos, scratchpads, agents, and
/// terminals into that one slot, suppressing whatever was there. The user is
/// free to split the content pane to make further slots.
///
/// `{{PROJECT}}`, `{{WASM}}`, `{{PANOPT_BIN}}`, and `{{PORT}}` are substituted
/// by [`render_layout`]; each may appear more than once.
const LAYOUT_TEMPLATE: &str = r#"// PANopt cockpit - generated by `panopt up`. Regenerated on each run.
// The sidebar plugin is pinned full-height on the LEFT (25%); a single content
// pane sits on the RIGHT. The sidebar swaps todos, scratchpads, agents, and
// terminals into that one pane - suppressed panes keep running, hidden.
layout {
    cwd "{{PROJECT}}"

    // The fixed shell of every tab: sidebar pinned left, the content pane on
    // the right flows into the `children` slot.
    tab_template name="ui" {
        pane split_direction="vertical" {
            pane size="25%" {
                plugin location="file:{{WASM}}" {
                    ws "{{PROJECT}}"
                    panopt_bin "{{PANOPT_BIN}}"
                    port "{{PORT}}"
                }
            }
            pane {
                children
            }
        }
    }

    // Initial state: the sidebar plus one empty document viewer.
    ui {
        pane command="{{PANOPT_BIN}}" {
            args "_viewer" "--slot" "main" "--port" "{{PORT}}"
        }
    }
}
"#;

/// Zellij's stock keybinding that enters scroll mode, and the cockpit's
/// replacement. [`render_config`] rewrites the first to the second so a bare
/// Ctrl-S is left unbound and reaches the focused pane - the todo form
/// (`panopt todo edit`) saves on it. Scroll mode moves to Ctrl-Shift-S.
///
/// Zellij layouts cannot carry keybindings (`keybinds` is not a layout node),
/// so this is applied to a generated config handed to Zellij via `--config`.
const SCROLL_BIND_FROM: &str = r#"bind "Ctrl s" { SwitchToMode "scroll"; }"#;
const SCROLL_BIND_TO: &str = r#"bind "Ctrl Shift s" { SwitchToMode "scroll"; }"#;

/// Zellij's stock Alt-N binding opens a shell pane. The cockpit retargets it
/// to send the `panopt:spawn-blank-pane` pipe to the sidebar plugin, which
/// spawns a fresh empty-viewer pane with its own routing slot - so the
/// sidebar can re-point it on later selections.
///
/// Why `Run "zellij" "action" "pipe" ...` instead of `MessagePlugin`: Zellij's
/// KDL parser folds `MessagePlugin`'s metadata fields (`name`, `payload`,
/// `cwd`, `launch_new`, ...) into the plugin's user-configuration map. The
/// runtime then keys plugin identity on `(URL, configuration)`, so a
/// `MessagePlugin` keybind whose configuration has any of those metadata
/// keys can never match a layout plugin whose configuration does not - Zellij
/// launches a *second* sidebar instance instead. `zellij action pipe` goes
/// through the running session's IPC bus and reaches the existing plugin
/// without that mismatch. The cost is a brief transient pane while the CLI
/// runs; `close_on_exit true` closes it the moment the pipe is sent.
const NEW_PANE_BIND_FROM: &str = r#"bind "Alt n" { NewPane; }"#;
const NEW_PANE_BIND_TO: &str = r#"bind "Alt n" { Run "zellij" "action" "pipe" "--name" "panopt:spawn-blank-pane" { close_on_exit true; }; }"#;

/// Zellij's stock close/quit keybinds, rewritten to pipe a request to the
/// sidebar plugin instead of acting immediately. The plugin acts as the
/// gatekeeper: it refuses the action when an active item would be lost and
/// otherwise force-closes through the plugin API. The `pipe` mechanism is the
/// same as Alt-N's rewrite - see [`NEW_PANE_BIND_FROM`] for why it goes through
/// `zellij action pipe` rather than `MessagePlugin`.
///
/// The defaults dump these in pane mode, tab mode, search mode (`x` =
/// CloseFocus), and a shared_except locked block (`Ctrl q` = Quit). Each FROM
/// here is the exact text the dump emits; [`str::replace`] catches every
/// occurrence so all modes funnel through the same pipe.
const CLOSE_FOCUS_BIND_FROM: &str = r#"bind "x" { CloseFocus; SwitchToMode "Normal"; }"#;
const CLOSE_FOCUS_BIND_TO: &str = r#"bind "x" { Run "zellij" "action" "pipe" "--name" "panopt:close-focus-request" { close_on_exit true; }; SwitchToMode "Normal"; }"#;
const CLOSE_TAB_BIND_FROM: &str = r#"bind "x" { CloseTab; SwitchToMode "Normal"; }"#;
const CLOSE_TAB_BIND_TO: &str = r#"bind "x" { Run "zellij" "action" "pipe" "--name" "panopt:close-tab-request" { close_on_exit true; }; SwitchToMode "Normal"; }"#;
const QUIT_BIND_FROM: &str = r#"bind "Ctrl q" { Quit; }"#;
const QUIT_BIND_TO: &str = r#"bind "Ctrl q" { Run "zellij" "action" "pipe" "--name" "panopt:quit-request" { close_on_exit true; }; }"#;

/// `panopt up` - ensure the daemon, then create or attach this project's
/// cockpit Zellij session.
pub fn run(plugin: Option<PathBuf>, port: u16) -> Result<()> {
    if std::env::var_os("ZELLIJ").is_some() {
        bail!("run `panopt up` from a plain shell, not inside Zellij");
    }

    daemon::ensure(port)?;
    mcp::ensure()?;

    let project = std::env::current_dir().context("reading the current directory")?;
    let project = std::fs::canonicalize(&project)
        .with_context(|| format!("no such directory: {}", project.display()))?;
    let session = session_name(&project);

    match session_state(&session) {
        SessionState::Live => {
            println!("attaching to cockpit `{session}`");
            let err = Command::new("zellij").arg("attach").arg(&session).exec();
            return Err(err).context("could not exec `zellij attach`");
        }
        SessionState::Dead => {
            // Quitting a cockpit leaves a dead, resurrectable Zellij session;
            // clear it so `panopt up` boots a fresh one. Daemon state (todos,
            // scratchpads) lives in SQLite and is unaffected.
            println!("clearing the dead cockpit `{session}`");
            let cleared = Command::new("zellij")
                .arg("delete-session")
                .arg(&session)
                .status()
                .context("running `zellij delete-session`")?;
            if !cleared.success() {
                bail!(
                    "could not clear the dead session `{session}`; \
                     remove it with `zellij delete-session {session}`"
                );
            }
        }
        SessionState::Absent => {}
    }

    let wasm = match plugin {
        Some(p) => p,
        None => default_plugin_wasm()
            .context("could not find the panopt-zellij plugin .wasm; pass --plugin <path>")?,
    };
    let layout = render_layout(&project, &wasm, port)?;
    let config = match render_config() {
        Ok(path) => Some(path),
        Err(e) => {
            eprintln!(
                "warning: could not prepare the cockpit's Zellij config ({e:#}); \
                 starting with your default keybindings - Ctrl-S in the todo form \
                 may be swallowed by Zellij, and Alt-N opens a shell instead of a \
                 blank viewer pane"
            );
            None
        }
    };
    println!("starting cockpit `{session}`");
    // `--new-session-with-layout` always creates a fresh session; plain
    // `--layout` alongside `--session` would instead try to add tabs to an
    // existing session of that name. `--config` points Zellij at the generated
    // cockpit config, which frees Ctrl-S for panes so the todo form saves on it.
    let mut zellij = Command::new("zellij");
    zellij.arg("--session").arg(&session);
    if let Some(config) = &config {
        zellij.arg("--config").arg(config);
    }
    zellij.arg("--new-session-with-layout").arg(&layout);
    let err = zellij.exec();
    Err(err).context("could not exec `zellij`")
}

/// The cockpit session name for a project: `panopt-<basename>-<hash>`. The
/// basename is reduced to characters Zellij accepts; the hash is a short
/// fingerprint of the canonical project path, so two projects sharing a
/// basename (`~/a/frontend`, `~/b/frontend`) land on distinct sessions
/// instead of one silently attaching to the other's cockpit.
fn session_name(project: &Path) -> String {
    let base = project
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project");
    let safe: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let hash = short_path_hash(project);
    format!("panopt-{safe}-{hash}")
}

/// Stable 7-hex-char fingerprint of the canonical project path. Used as the
/// disambiguating suffix on the cockpit session name; see [`session_name`].
fn short_path_hash(project: &Path) -> String {
    use std::hash::{Hash, Hasher};
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    project.hash(&mut hasher);
    let h = hasher.finish();
    format!("{h:016x}").chars().take(7).collect()
}

/// Whether a Zellij session named `name` exists, and if so whether it is live
/// or dead (exited but still resurrectable).
enum SessionState {
    Absent,
    Live,
    Dead,
}

fn session_state(name: &str) -> SessionState {
    let Ok(out) = Command::new("zellij").arg("list-sessions").output() else {
        return SessionState::Absent;
    };
    let text = strip_ansi(&String::from_utf8_lossy(&out.stdout));
    for line in text.lines() {
        if line.split_whitespace().next() == Some(name) {
            return if line.contains("EXITED") {
                SessionState::Dead
            } else {
                SessionState::Live
            };
        }
    }
    SessionState::Absent
}

/// Drop ANSI escape sequences so `zellij list-sessions` output can be parsed.
fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' {
            // Skip a CSI sequence up to and including its final letter.
            for n in chars.by_ref() {
                if n.is_ascii_alphabetic() {
                    break;
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Locate the plugin `.wasm` from a dev build, relative to this binary
/// (`<repo>/target/<profile>/panopt`).
fn default_plugin_wasm() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let repo = exe.ancestors().nth(3)?;
    let wasm = repo.join("crates/panopt-zellij/target/wasm32-wasip1/release/panopt-zellij.wasm");
    wasm.is_file().then_some(wasm)
}

/// Render the cockpit layout for `project`, write it to disk, return its path.
fn render_layout(project: &Path, wasm: &Path, port: u16) -> Result<PathBuf> {
    let panopt_bin = std::env::current_exe().context("locating the panopt binary")?;
    let body = LAYOUT_TEMPLATE
        .replace("{{PROJECT}}", &project.to_string_lossy())
        .replace("{{WASM}}", &wasm.to_string_lossy())
        .replace("{{PANOPT_BIN}}", &panopt_bin.to_string_lossy())
        .replace("{{PORT}}", &port.to_string());
    let path = paths::cockpit_layout()?;
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// Free Ctrl-S for panes by retargeting Zellij's scroll-mode keybinding to
/// Ctrl-Shift-S. Returns the rewritten config and whether the binding was
/// actually found - a reformatted or unusually customized config may not carry
/// it in the expected form.
fn retarget_scroll_binding(base: &str) -> (String, bool) {
    let tweaked = base.replace(SCROLL_BIND_FROM, SCROLL_BIND_TO);
    let changed = tweaked != base;
    (tweaked, changed)
}

/// Retarget Zellij's Alt-N keybinding to `Run` of `zellij action pipe`, which
/// pipes a message to the sidebar plugin telling it to spawn a blank viewer
/// pane.
fn retarget_new_pane_binding(base: &str) -> (String, bool) {
    let tweaked = base.replace(NEW_PANE_BIND_FROM, NEW_PANE_BIND_TO);
    let changed = tweaked != base;
    (tweaked, changed)
}

/// Retarget every CloseFocus/CloseTab/Quit keybind to `Run` of
/// `zellij action pipe`, sending the request to the sidebar plugin instead of
/// acting immediately. The plugin gates these against active items and either
/// refuses (showing a floating dialog) or force-closes via the plugin API,
/// which bypasses the rewritten keybinds.
///
/// The returned tuple reports whether each rewrite was found - users with a
/// reformatted or heavily-customized config may have moved them; we warn so
/// the user knows the gate has gaps. The default Zellij dump emits the
/// CloseFocus binding in multiple modes; `str::replace` catches every copy.
fn retarget_close_bindings(base: &str) -> (String, bool, bool, bool) {
    let after_close_focus = base.replace(CLOSE_FOCUS_BIND_FROM, CLOSE_FOCUS_BIND_TO);
    let close_focus_changed = after_close_focus != base;
    let after_close_tab = after_close_focus.replace(CLOSE_TAB_BIND_FROM, CLOSE_TAB_BIND_TO);
    let close_tab_changed = after_close_tab != after_close_focus;
    let after_quit = after_close_tab.replace(QUIT_BIND_FROM, QUIT_BIND_TO);
    let quit_changed = after_quit != after_close_tab;
    (
        after_quit,
        close_focus_changed,
        close_tab_changed,
        quit_changed,
    )
}

/// Locate the Zellij config file Zellij itself would load, following its own
/// lookup order: `$ZELLIJ_CONFIG_FILE`, `$ZELLIJ_CONFIG_DIR/config.kdl`,
/// `$XDG_CONFIG_HOME/zellij/config.kdl`, then `~/.config/zellij/config.kdl`.
/// `None` when the user keeps no config and relies on Zellij's defaults.
fn user_zellij_config() -> Option<PathBuf> {
    if let Some(file) = std::env::var_os("ZELLIJ_CONFIG_FILE") {
        let path = PathBuf::from(file);
        if path.is_file() {
            return Some(path);
        }
    }
    let config_kdl = |dir: PathBuf| {
        let path = dir.join("config.kdl");
        path.is_file().then_some(path)
    };
    if let Some(dir) = std::env::var_os("ZELLIJ_CONFIG_DIR") {
        if let Some(path) = config_kdl(PathBuf::from(dir)) {
            return Some(path);
        }
    }
    if let Some(dir) = std::env::var_os("XDG_CONFIG_HOME") {
        if let Some(path) = config_kdl(PathBuf::from(dir).join("zellij")) {
            return Some(path);
        }
    }
    dirs::home_dir().and_then(|home| config_kdl(home.join(".config").join("zellij")))
}

/// The Zellij config to derive the cockpit's from: the user's own config, or -
/// when they keep none - Zellij's built-in defaults via `zellij setup
/// --dump-config`.
fn base_zellij_config() -> Result<String> {
    if let Some(path) = user_zellij_config() {
        return std::fs::read_to_string(&path)
            .with_context(|| format!("reading the Zellij config {}", path.display()));
    }
    let out = Command::new("zellij")
        .args(["setup", "--dump-config"])
        .output()
        .context("running `zellij setup --dump-config`")?;
    if !out.status.success() {
        bail!("`zellij setup --dump-config` exited with a failure");
    }
    String::from_utf8(out.stdout).context("`zellij setup --dump-config` produced invalid UTF-8")
}

/// Generate the cockpit's Zellij config - the user's config with Ctrl-S freed
/// for panes so the todo form's save keybinding reaches it, and Alt-N
/// retargeted to spawn a blank viewer pane via the sidebar plugin - write it
/// to disk, and return its path. Regenerated on each run, so it tracks the
/// user's own config.
fn render_config() -> Result<PathBuf> {
    let base = base_zellij_config()?;
    let (tweaked, scroll_changed) = retarget_scroll_binding(&base);
    if !scroll_changed {
        eprintln!(
            "warning: Zellij's `Ctrl s` scroll binding was not found in the \
             expected form, so it could not be remapped; Ctrl-S in the todo \
             form may be swallowed by Zellij"
        );
    }
    let (tweaked, new_pane_changed) = retarget_new_pane_binding(&tweaked);
    if !new_pane_changed {
        eprintln!(
            "warning: Zellij's `Alt n` `NewPane` binding was not found in the \
             expected form, so it could not be remapped; Alt-N will open a \
             shell rather than a blank viewer pane"
        );
    }
    let (tweaked, close_focus_changed, close_tab_changed, quit_changed) =
        retarget_close_bindings(&tweaked);
    if !close_focus_changed {
        eprintln!(
            "warning: Zellij's `CloseFocus` binding was not found in the \
             expected form, so it could not be gated; closing a pane will \
             bypass the active-item guard"
        );
    }
    if !close_tab_changed {
        eprintln!(
            "warning: Zellij's `CloseTab` binding was not found in the \
             expected form, so it could not be gated; closing a tab will \
             bypass the active-item guard"
        );
    }
    if !quit_changed {
        eprintln!(
            "warning: Zellij's `Ctrl q` `Quit` binding was not found in the \
             expected form, so it could not be gated; quitting will bypass \
             the active-item guard"
        );
    }
    let body = format!(
        "// PANopt cockpit Zellij config - generated by `panopt up`, regenerated\n\
         // each run from your own Zellij config. Zellij's Ctrl-S (scroll mode)\n\
         // is remapped to Ctrl-Shift-S so a bare Ctrl-S reaches panes: the todo\n\
         // form (`panopt todo edit`) saves on it. Alt-N is retargeted to pipe\n\
         // a `panopt:spawn-blank-pane` message to the sidebar plugin, which\n\
         // spawns a blank viewer pane with its own routing slot. CloseFocus,\n\
         // CloseTab, and Quit are retargeted to pipe close-request messages to\n\
         // the sidebar, which gates them against active agents/commands/terminals.\n\
         {tweaked}"
    );
    let path = paths::cockpit_config()?;
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::{
        retarget_close_bindings, retarget_new_pane_binding, retarget_scroll_binding, session_name,
        strip_ansi, LAYOUT_TEMPLATE,
    };
    use std::path::Path;

    #[test]
    fn session_name_sanitizes_the_basename() {
        let n = session_name(Path::new("/Users/x/p/panopt-demo"));
        assert!(n.starts_with("panopt-panopt-demo-"), "got {n}");
        let n2 = session_name(Path::new("/a/b/My Proj.v2"));
        assert!(n2.starts_with("panopt-My-Proj-v2-"), "got {n2}");
    }

    #[test]
    fn session_name_disambiguates_same_basename() {
        let a = session_name(Path::new("/home/u/a/frontend"));
        let b = session_name(Path::new("/home/u/b/frontend"));
        assert_ne!(a, b);
        assert!(a.starts_with("panopt-frontend-"));
        assert!(b.starts_with("panopt-frontend-"));
    }

    #[test]
    fn strip_ansi_removes_escape_sequences() {
        assert_eq!(strip_ansi("\u{1b}[32;1mname\u{1b}[m rest"), "name rest");
    }

    #[test]
    fn retarget_scroll_binding_moves_ctrl_s_to_ctrl_shift_s() {
        let base = "    bind \"Ctrl s\" { SwitchToMode \"scroll\"; }\n";
        let (tweaked, changed) = retarget_scroll_binding(base);
        assert!(changed);
        assert_eq!(
            tweaked,
            "    bind \"Ctrl Shift s\" { SwitchToMode \"scroll\"; }\n"
        );
        // The scroll-mode exit binding (`Ctrl s` -> normal) is a different
        // string and must be left untouched.
        let exit = "bind \"Ctrl s\" { SwitchToMode \"normal\"; }";
        assert_eq!(retarget_scroll_binding(exit), (exit.to_string(), false));
    }

    #[test]
    fn retarget_scroll_binding_reports_when_absent() {
        let (text, changed) = retarget_scroll_binding("keybinds {}\n");
        assert!(!changed);
        assert_eq!(text, "keybinds {}\n");
    }

    #[test]
    fn retarget_new_pane_binding_swaps_in_the_pipe_action() {
        let base = "    bind \"Alt n\" { NewPane; }\n";
        let (tweaked, changed) = retarget_new_pane_binding(base);
        assert!(changed);
        // The pipe goes through Zellij's IPC bus rather than MessagePlugin, so
        // it reaches the existing sidebar without the user-config mismatch
        // that would otherwise have Zellij spawn a second sidebar instance.
        assert!(
            tweaked.contains("Run \"zellij\" \"action\" \"pipe\""),
            "expected the Run action with `zellij action pipe`: {tweaked}"
        );
        assert!(tweaked.contains("\"panopt:spawn-blank-pane\""));
        // The transient pane must close itself as soon as the CLI exits, so
        // the user just sees a brief flash and then the new viewer pane.
        assert!(tweaked.contains("close_on_exit true"));
    }

    #[test]
    fn retarget_new_pane_binding_reports_when_absent() {
        let (text, changed) = retarget_new_pane_binding("keybinds {}\n");
        assert!(!changed);
        assert_eq!(text, "keybinds {}\n");
    }

    #[test]
    fn retarget_close_bindings_funnels_all_three_actions_through_pipes() {
        // A fragment that mirrors the default Zellij dump: CloseFocus appears
        // in two modes (pane and search) - both must be rewritten - and
        // CloseTab and Quit appear once each.
        let base = "\
            pane {\n        \
                bind \"x\" { CloseFocus; SwitchToMode \"Normal\"; }\n    \
            }\n    \
            tab {\n        \
                bind \"x\" { CloseTab; SwitchToMode \"Normal\"; }\n    \
            }\n    \
            search {\n        \
                bind \"x\" { CloseFocus; SwitchToMode \"Normal\"; }\n    \
            }\n    \
            shared_except \"locked\" {\n        \
                bind \"Ctrl q\" { Quit; }\n    \
            }\n";
        let (tweaked, close_focus, close_tab, quit) = retarget_close_bindings(base);
        assert!(close_focus, "CloseFocus binding must be rewritten");
        assert!(close_tab, "CloseTab binding must be rewritten");
        assert!(quit, "Quit binding must be rewritten");
        // Every destructive action goes through the same pipe pattern so the
        // sidebar plugin is the single gatekeeper.
        assert!(tweaked.contains("\"panopt:close-focus-request\""));
        assert!(tweaked.contains("\"panopt:close-tab-request\""));
        assert!(tweaked.contains("\"panopt:quit-request\""));
        // Both CloseFocus occurrences (pane and search modes) are caught.
        assert_eq!(tweaked.matches("\"panopt:close-focus-request\"").count(), 2);
        // No raw destructive action remains: every path is gated.
        assert!(!tweaked.contains("CloseFocus"));
        assert!(!tweaked.contains("CloseTab"));
        assert!(!tweaked.contains("{ Quit; }"));
        // The mode return is preserved so the user still leaves pane/tab mode
        // after the pipe is sent - matching the original UX shape.
        assert!(tweaked.contains("SwitchToMode \"Normal\""));
        // Transient pipe panes close themselves the moment the CLI exits.
        assert!(tweaked.contains("close_on_exit true"));
    }

    #[test]
    fn retarget_close_bindings_reports_when_absent() {
        let (text, close_focus, close_tab, quit) = retarget_close_bindings("keybinds {}\n");
        assert!(!close_focus);
        assert!(!close_tab);
        assert!(!quit);
        assert_eq!(text, "keybinds {}\n");
    }

    #[test]
    fn layout_template_has_every_placeholder_filled() {
        let body = LAYOUT_TEMPLATE
            .replace("{{PROJECT}}", "/proj")
            .replace("{{WASM}}", "/w.wasm")
            .replace("{{PANOPT_BIN}}", "/bin/panopt")
            .replace("{{PORT}}", "7600");
        assert!(!body.contains("{{"), "unsubstituted placeholder: {body}");
        assert!(body.contains("file:/w.wasm"));
        assert!(body.contains("port \"7600\""));
    }

    #[test]
    fn layout_template_pins_the_sidebar_and_starts_one_viewer() {
        // The sidebar plugin lives in the `ui` tab template, so it is pinned.
        assert!(LAYOUT_TEMPLATE.contains("tab_template name=\"ui\""));
        // The one content pane starts as an empty viewer; no swap layouts.
        assert!(LAYOUT_TEMPLATE.contains("\"_viewer\""));
        assert!(LAYOUT_TEMPLATE.contains("\"--slot\" \"main\""));
        assert!(LAYOUT_TEMPLATE.contains("children"));
        assert!(!LAYOUT_TEMPLATE.contains("swap_tiled_layout"));
    }
}
