//! `panopt up` - boot or attach the cockpit.

use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

use crate::{daemon, mcp, paths};

/// The cockpit layout: a sidebar plugin pane and one initial agent pane.
/// `{{PROJECT}}`, `{{WASM}}`, and `{{PANOPT_BIN}}` are substituted by
/// [`render_layout`].
const LAYOUT_TEMPLATE: &str = r#"// PANopt cockpit - generated by `panopt up`. Regenerated on each run.
layout {
    cwd "{{PROJECT}}"
    pane split_direction="vertical" {
        pane size="25%" {
            plugin location="file:{{WASM}}" {
                ws "{{PROJECT}}"
                panopt_bin "{{PANOPT_BIN}}"
            }
        }
        pane command="{{PANOPT_BIN}}" {
            args "_agent"
        }
    }
}
"#;

/// `panopt up` - ensure the daemon, then create or attach this project's
/// cockpit Zellij session.
pub fn run(plugin: Option<PathBuf>, port: u16) -> Result<()> {
    if std::env::var_os("ZELLIJ").is_some() {
        bail!("run `panopt up` from a plain shell, not inside Zellij");
    }

    daemon::ensure(port)?;
    mcp::ensure()?;

    let project = std::env::current_dir().context("reading the current directory")?;
    let project = std::fs::canonicalize(&project)
        .with_context(|| format!("no such directory: {}", project.display()))?;
    let session = session_name(&project);

    match session_state(&session) {
        SessionState::Live => {
            println!("attaching to cockpit `{session}`");
            let err = Command::new("zellij").arg("attach").arg(&session).exec();
            return Err(err).context("could not exec `zellij attach`");
        }
        SessionState::Dead => {
            // Quitting a cockpit leaves a dead, resurrectable Zellij session;
            // clear it so `panopt up` boots a fresh one. Daemon state (todos,
            // scratchpads) lives in SQLite and is unaffected.
            println!("clearing the dead cockpit `{session}`");
            let cleared = Command::new("zellij")
                .arg("delete-session")
                .arg(&session)
                .status()
                .context("running `zellij delete-session`")?;
            if !cleared.success() {
                bail!(
                    "could not clear the dead session `{session}`; \
                     remove it with `zellij delete-session {session}`"
                );
            }
        }
        SessionState::Absent => {}
    }

    let wasm = match plugin {
        Some(p) => p,
        None => default_plugin_wasm()
            .context("could not find the panopt-zellij plugin .wasm; pass --plugin <path>")?,
    };
    let layout = render_layout(&project, &wasm)?;
    println!("starting cockpit `{session}`");
    // `--new-session-with-layout` always creates a fresh session; plain
    // `--layout` alongside `--session` would instead try to add tabs to an
    // existing session of that name.
    let err = Command::new("zellij")
        .arg("--session")
        .arg(&session)
        .arg("--new-session-with-layout")
        .arg(&layout)
        .exec();
    Err(err).context("could not exec `zellij`")
}

/// The cockpit session name for a project: `panopt-<basename>`, with the
/// basename reduced to characters Zellij accepts in a session name.
fn session_name(project: &Path) -> String {
    let base = project
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project");
    let safe: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    format!("panopt-{safe}")
}

/// Whether a Zellij session named `name` exists, and if so whether it is live
/// or dead (exited but still resurrectable).
enum SessionState {
    Absent,
    Live,
    Dead,
}

fn session_state(name: &str) -> SessionState {
    let Ok(out) = Command::new("zellij").arg("list-sessions").output() else {
        return SessionState::Absent;
    };
    let text = strip_ansi(&String::from_utf8_lossy(&out.stdout));
    for line in text.lines() {
        if line.split_whitespace().next() == Some(name) {
            return if line.contains("EXITED") {
                SessionState::Dead
            } else {
                SessionState::Live
            };
        }
    }
    SessionState::Absent
}

/// Drop ANSI escape sequences so `zellij list-sessions` output can be parsed.
fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' {
            // Skip a CSI sequence up to and including its final letter.
            for n in chars.by_ref() {
                if n.is_ascii_alphabetic() {
                    break;
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Locate the plugin `.wasm` from a dev build, relative to this binary
/// (`<repo>/target/<profile>/panopt`).
fn default_plugin_wasm() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let repo = exe.ancestors().nth(3)?;
    let wasm =
        repo.join("crates/panopt-zellij/target/wasm32-wasip1/release/panopt-zellij.wasm");
    wasm.is_file().then_some(wasm)
}

/// Render the cockpit layout for `project`, write it to disk, return its path.
fn render_layout(project: &Path, wasm: &Path) -> Result<PathBuf> {
    let panopt_bin = std::env::current_exe().context("locating the panopt binary")?;
    let body = LAYOUT_TEMPLATE
        .replace("{{PROJECT}}", &project.to_string_lossy())
        .replace("{{WASM}}", &wasm.to_string_lossy())
        .replace("{{PANOPT_BIN}}", &panopt_bin.to_string_lossy());
    let path = paths::cockpit_layout()?;
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::{session_name, strip_ansi, LAYOUT_TEMPLATE};
    use std::path::Path;

    #[test]
    fn session_name_sanitizes_the_basename() {
        assert_eq!(
            session_name(Path::new("/Users/x/p/panopt-demo")),
            "panopt-panopt-demo"
        );
        assert_eq!(session_name(Path::new("/a/b/My Proj.v2")), "panopt-My-Proj-v2");
    }

    #[test]
    fn strip_ansi_removes_escape_sequences() {
        assert_eq!(strip_ansi("\u{1b}[32;1mname\u{1b}[m rest"), "name rest");
    }

    #[test]
    fn layout_template_has_every_placeholder_filled() {
        let body = LAYOUT_TEMPLATE
            .replace("{{PROJECT}}", "/proj")
            .replace("{{WASM}}", "/w.wasm")
            .replace("{{PANOPT_BIN}}", "/bin/panopt");
        assert!(!body.contains("{{"), "unsubstituted placeholder: {body}");
        assert!(body.contains("file:/w.wasm"));
    }
}
